import random

def menu():
    print("Would you like to Play or Quit?")
    choice1 = input()
    choice1 = choice1.lower()
    if choice1 == "play":
        #############################################################################
        #                           dealing the cards:                              #
        #############################################################################
        print("How many cards would you like to play with?(An even number between 4-20 - Each Player will have 1-10)")
        DeckSize = input()
        DeckSize = int(DeckSize)
        if DeckSize<4 or DeckSize>20 or DeckSize % 2 == 1:
            print("Invalid response, you have been returned to the menu.")
            menu()
        #To read the text file and create the dog cards:
        NameList = open("dogs.txt")
        Cards = []
        Line = int(0)
        while Line < DeckSize:
            Cards.append(NameList.readline())
            Cards.append(random.randrange(1, 6))
            Cards.append(random.randrange(1, 101))
            Cards.append(random.randrange(1, 11))
            Cards.append(random.randrange(1, 11))
            Line = Line + 1
        NameList.close()
        Limit = len(Cards)
        PlayerPile = []
        ComputerPile = []
        PlayerCard = int(0)
        ComputerCard = int(0)
        while PlayerCard < Limit:
            PlayerPile.append(Cards[PlayerCard])
            PlayerCard = PlayerCard + 1
            PlayerPile.append(Cards[PlayerCard])
            PlayerCard = PlayerCard + 1
            PlayerPile.append(Cards[PlayerCard])
            PlayerCard = PlayerCard + 1
            PlayerPile.append(Cards[PlayerCard])
            PlayerCard = PlayerCard + 1
            PlayerPile.append(Cards[PlayerCard])
            PlayerCard = PlayerCard + 1
            PlayerCard = PlayerCard + 5
        while ComputerCard < Limit:
            ComputerCard = ComputerCard + 5
            ComputerPile.append(Cards[ComputerCard])
            ComputerCard = ComputerCard + 1
            ComputerPile.append(Cards[ComputerCard])
            ComputerCard = ComputerCard + 1
            ComputerPile.append(Cards[ComputerCard])
            ComputerCard = ComputerCard + 1
            ComputerPile.append(Cards[ComputerCard])
            ComputerCard = ComputerCard + 1
            ComputerPile.append(Cards[ComputerCard])
            ComputerCard = ComputerCard + 1
         #Now each player has an array containing their cards.

        #############################################################################
        #                           playing the game:                               #
        #############################################################################
        PlayerScore = int(0)
        ComputerPileCount = int(0)
        ComputerScore = int(0)
        while len(PlayerPile) > 0 and len(ComputerPile) > 0:
            print ("You want to have the higher stat in exercise, intelligence and friendliness, but the lower stat in drool. Here is your top card:")
            print (" ")
            PlayerName = PlayerPile[0]
            print ("Name: ", PlayerPile[0])
            PlayerExercise = int(PlayerPile[1])
            print ("Exercise: ", PlayerExercise)
            PlayerIntelligence = int(PlayerPile[2])
            print ("Intelligence: ", PlayerIntelligence)
            PlayerFriendliness = int(PlayerPile[3])
            print ("Friendliness: ", PlayerFriendliness)
            PlayerDrool = int(PlayerPile[4])
            print ("Drool: ", PlayerDrool)
            ComputerName = ComputerPile[0]
            ComputerExercise = int(ComputerPile[1])
            ComputerIntelligence = int(ComputerPile[2])
            ComputerFriendliness = int(ComputerPile[3])
            ComputerDrool = int(ComputerPile[4])
            Category = " "
            while Category != "intelligence" and Category != "exercise" and Category != "drool" and Category != "friendliness":
                print ("Which category do you choose?")
                Category = input()
                Category = Category.lower()
            if Category == "exercise":
                if PlayerExercise > ComputerExercise:
                    print ("You win this round, Congratulations!")
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    PlayerPile.append(PlayerName)
                    PlayerPile.append(PlayerExercise)
                    PlayerPile.append(PlayerIntelligence)
                    PlayerPile.append(PlayerFriendliness)
                    PlayerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                elif PlayerExercise < ComputerExercise:
                    print ("You lost this round, Unlunky!")
                    ComputerScore = ComputerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    ComputerPile.append(ComputerName)
                    ComputerPile.append(ComputerExercise)
                    ComputerPile.append(ComputerIntelligence)
                    ComputerPile.append(ComputerFriendliness)
                    ComputerPile.append(ComputerDrool)
                elif PlayerExercise == ComputerExercise:
                    print ("A draw!")
                    ComputerScore = ComputerScore + 1
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
            elif Category == "intelligence":
                if PlayerIntelligence > ComputerIntelligence:
                    print ("You win this round, Congratulations!")
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    PlayerPile.append(PlayerName)
                    PlayerPile.append(PlayerExercise)
                    PlayerPile.append(PlayerIntelligence)
                    PlayerPile.append(PlayerFriendliness)
                    PlayerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                elif PlayerIntelligence < ComputerIntelligence:
                    print ("You lost this round, Unlunky!")
                    ComputerScore = ComputerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    ComputerPile.append(ComputerName)
                    ComputerPile.append(ComputerExercise)
                    ComputerPile.append(ComputerIntelligence)
                    ComputerPile.append(ComputerFriendliness)
                    ComputerPile.append(ComputerDrool)
                elif PlayerIntelligence == ComputerIntelligence:
                    print ("A draw!")
                    ComputerScore = ComputerScore + 1
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
            elif Category == "friendliness":
                if PlayerFriendliness > ComputerFriendliness:
                    print ("You win this round, Congratulations!")
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    PlayerPile.append(PlayerName)
                    PlayerPile.append(PlayerExercise)
                    PlayerPile.append(PlayerIntelligence)
                    PlayerPile.append(PlayerFriendliness)
                    PlayerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                elif PlayerFriendliness < ComputerFriendliness:
                    print ("You lost this round, Unlunky!")
                    ComputerScore = ComputerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    ComputerPile.append(ComputerName)
                    ComputerPile.append(ComputerExercise)
                    ComputerPile.append(ComputerIntelligence)
                    ComputerPile.append(ComputerFriendliness)
                    ComputerPile.append(ComputerDrool)
                elif PlayerFriendliness == ComputerFriendliness:
                    print ("A draw!")
                    ComputerScore = ComputerScore + 1
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
            elif Category == "drool":
                if PlayerDrool < ComputerDrool:
                    print ("You win this round, Congratulations!")
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    PlayerPile.append(PlayerName)
                    PlayerPile.append(PlayerExercise)
                    PlayerPile.append(PlayerIntelligence)
                    PlayerPile.append(PlayerFriendliness)
                    PlayerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                    PlayerScore = PlayerScore + 1
                elif PlayerDrool > ComputerDrool:
                    print ("You lost this round, Unlunky!")
                    ComputerScore = ComputerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    ComputerPile.append(ComputerName)
                    ComputerPile.append(ComputerExercise)
                    ComputerPile.append(ComputerIntelligence)
                    ComputerPile.append(ComputerFriendliness)
                    ComputerPile.append(ComputerDrool)
                elif PlayerDrool == ComputerDrool:
                    print ("A draw!")
                    ComputerScore = ComputerScore + 1
                    PlayerScore = PlayerScore + 1
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    PlayerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.pop(0)
                    ComputerPile.append(PlayerName)
                    ComputerPile.append(PlayerExercise)
                    ComputerPile.append(PlayerIntelligence)
                    ComputerPile.append(PlayerFriendliness)
                    ComputerPile.append(PlayerDrool)
                    PlayerPile.append(ComputerName)
                    PlayerPile.append(ComputerExercise)
                    PlayerPile.append(ComputerIntelligence)
                    PlayerPile.append(ComputerFriendliness)
                    PlayerPile.append(ComputerDrool)
                print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
            if len(PlayerPile) > 0 and len(ComputerPile) > 0:
                print ("It is now the computers turn. Here is your card:")
                PlayerName = PlayerPile[0]
                print ("Name: ", PlayerPile[0])
                PlayerExercise = int(PlayerPile[1])
                print ("Exercise: ", PlayerExercise)
                PlayerIntelligence = int(PlayerPile[2])
                print ("Intelligence: ", PlayerIntelligence)
                PlayerFriendliness = int(PlayerPile[3])
                print ("Friendliness: ", PlayerFriendliness)
                PlayerDrool = int(PlayerPile[4])
                print ("Drool: ", PlayerDrool)
                ComputerName = ComputerPile[0]
                ComputerExercise = int(ComputerPile[1])
                ComputerIntelligence = int(ComputerPile[2])
                ComputerFriendliness = int(ComputerPile[3])
                ComputerDrool = int(ComputerPile[4])
                ComputerChoice = str(random.randrange(1, 5))
                if ComputerChoice == "1":
                    print ("The computer has chosen the Exercise category")
                    if PlayerExercise > ComputerExercise:
                        print ("You win this round, Congratulations!")
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        PlayerPile.append(PlayerName)
                        PlayerPile.append(PlayerExercise)
                        PlayerPile.append(PlayerIntelligence)
                        PlayerPile.append(PlayerFriendliness)
                        PlayerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    elif PlayerExercise < ComputerExercise:
                        print ("You lost this round, Unlunky!")
                        ComputerScore = ComputerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        ComputerPile.append(ComputerName)
                        ComputerPile.append(ComputerExercise)
                        ComputerPile.append(ComputerIntelligence)
                        ComputerPile.append(ComputerFriendliness)
                        ComputerPile.append(ComputerDrool)
                    elif PlayerExercise == ComputerExercise:
                        print ("A draw!")
                        ComputerScore = ComputerScore + 1
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
                elif ComputerChoice == "2":
                    print ("The computer has chosen the Intelligence category")
                    if PlayerIntelligence > ComputerIntelligence:
                        print ("You win this round, Congratulations!")
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        PlayerPile.append(PlayerName)
                        PlayerPile.append(PlayerExercise)
                        PlayerPile.append(PlayerIntelligence)
                        PlayerPile.append(PlayerFriendliness)
                        PlayerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    elif PlayerIntelligence < ComputerIntelligence:
                        print ("You lost this round, Unlunky!")
                        ComputerScore = ComputerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        ComputerPile.append(ComputerName)
                        ComputerPile.append(ComputerExercise)
                        ComputerPile.append(ComputerIntelligence)
                        ComputerPile.append(ComputerFriendliness)
                        ComputerPile.append(ComputerDrool)
                    elif PlayerIntelligence == ComputerIntelligence:
                        print ("A draw!")
                        ComputerScore = ComputerScore + 1
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
                elif ComputerChoice == "3":
                    print ("The computer has chosen the Friendliness category")
                    if PlayerFriendliness > ComputerFriendliness:
                        print ("You win this round, Congratulations!")
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        PlayerPile.append(PlayerName)
                        PlayerPile.append(PlayerExercise)
                        PlayerPile.append(PlayerIntelligence)
                        PlayerPile.append(PlayerFriendliness)
                        PlayerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    elif PlayerFriendliness < ComputerFriendliness:
                        print ("You lost this round, Unlunky!")
                        ComputerScore = ComputerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        ComputerPile.append(ComputerName)
                        ComputerPile.append(ComputerExercise)
                        ComputerPile.append(ComputerIntelligence)
                        ComputerPile.append(ComputerFriendliness)
                        ComputerPile.append(ComputerDrool)
                    elif PlayerFriendliness == ComputerFriendliness:
                        print ("A draw!")
                        ComputerScore = ComputerScore + 1
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
                elif ComputerChoice == "4":
                    print ("The computer has chosen the Drool category")
                    if PlayerDrool < ComputerDrool:
                        print ("You win this round, Congratulations!")
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        PlayerPile.append(PlayerName)
                        PlayerPile.append(PlayerExercise)
                        PlayerPile.append(PlayerIntelligence)
                        PlayerPile.append(PlayerFriendliness)
                        PlayerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                        PlayerScore = PlayerScore + 1
                    elif PlayerDrool > ComputerDrool:
                        print ("You lost this round, Unlunky!")
                        ComputerScore = ComputerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        ComputerPile.append(ComputerName)
                        ComputerPile.append(ComputerExercise)
                        ComputerPile.append(ComputerIntelligence)
                        ComputerPile.append(ComputerFriendliness)
                        ComputerPile.append(ComputerDrool)
                    elif PlayerDrool == ComputerDrool:
                        print ("A draw!")
                        ComputerScore = ComputerScore + 1
                        PlayerScore = PlayerScore + 1
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        PlayerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.pop(0)
                        ComputerPile.append(PlayerName)
                        ComputerPile.append(PlayerExercise)
                        ComputerPile.append(PlayerIntelligence)
                        ComputerPile.append(PlayerFriendliness)
                        ComputerPile.append(PlayerDrool)
                        PlayerPile.append(ComputerName)
                        PlayerPile.append(ComputerExercise)
                        PlayerPile.append(ComputerIntelligence)
                        PlayerPile.append(ComputerFriendliness)
                        PlayerPile.append(ComputerDrool)
                    print ("The score is now ", PlayerScore, " to you, and ", ComputerScore, " to the computer.")
                else:
                    print("And the final score is: ")
                    print(PlayerScore, " to you,")
                    print("And ", ComputerScore, " to the computer!")      
        print("And the final score is: ")
        print(PlayerScore, " to you,")
        print("And ", ComputerScore, " to the computer!")
    elif choice1 == "quit":
        print("Thank you for playing :)")
    else:
        print("Invalid response, please try again.")







menu()
        

